// DO NOT EDIT — generated by scripts/generate_feature_flags.py
// Source of truth: moonshot_core/data/feature_flags.txt
export const FeatureFlagNames = {
  AIVET_Q42026_MOON774: "AIVET_Q42026_MOON774",
} as const;

export type FeatureFlagName =
  (typeof FeatureFlagNames)[keyof typeof FeatureFlagNames];
