from pydantic import BaseModel


class ConnectorResponseEntity(BaseModel):
    """
    ConnectorResponseEntity represents the response generated by a connector along with its context.

    Attributes:
        response (str): The response generated by the connector.
        context (list): The context in which the response was generated.
    """

    class Config:
        arbitrary_types_allowed = True

    # The response generated by the connector
    response: str = ""

    # The context in which the response was generated
    context: list = []
