from typing import Dict, List
import pytest
from pathlib import Path
from dirty_equals import IsStr

from adapters.driven.repository.sqlalchemy.llm_provider_adapter import LLMProviderAdapter
from adapters.driven.repository.sqlalchemy.llm_provider_models import LLMProviderModel
from adapters.driven.repository.sqlalchemy.session_manager import SessionManager
from domain.entities.provider_entity import ProviderEntity


@pytest.fixture(scope="function")
def test_db_path():
    """Create a temporary database path for testing."""
    # Use the specified path relative to moonshot_core
    # From test file: moonshot_core/tests/adapters/driven/repository/sqlalchemy/test_llm_provider_adapter.py
    # Go up 6 levels to reach moonshot_core root
    moonshot_core_root: Path = Path(__file__).parent.parent.parent.parent.parent.parent
    db_path: Path = moonshot_core_root / "data" / "database" / "moonshot_pytest.db"
    
    # Clean up any existing database
    if db_path.exists():
        db_path.unlink()
    
    yield str(db_path)
    
    # TODO: Determine if DB is required for other tests that rely on LLM Provider Adapter
    # # Cleanup after test
    # if db_path.exists():
    #     db_path.unlink()

@pytest.fixture(scope="function")
def test_db_env(test_db_path, monkeypatch):
    """Set up test database environment variable and reset SessionManager."""
    # Set the environment variable
    monkeypatch.setenv("MOONSHOT_DB_PATH", test_db_path)
    
    # Reset the SessionManager singleton to pick up the new database path
    SessionManager.reset_instance()
    
    yield
    
    # Cleanup: reset the singleton and remove env var
    SessionManager.reset_instance()
    monkeypatch.delenv("MOONSHOT_DB_PATH", raising=False)

@pytest.fixture
def llm_provider_adapter(test_db_env):
    """Create an LLMProviderAdapter instance with real SessionManager."""
    adapter = LLMProviderAdapter()
    return adapter

def generate_expected_llm_provider_entity_dict(provider_name: str, id: str | None = None) -> Dict[str, any]:
    """This dict is to test against ProviderEntity.model_dump() due to 'id' attribute is not deterministic (generated by the DB).
    Will need to be updated when ProviderEntity is modified.
    """
    return {
            "id": IsStr() if id is None else id,
            "name": provider_name,
            "defaultModel": "",
            "modelTextboxExplanation": "",
            "defaultConfigPairs": {},
            "modelToken": ""
        }


class TestLLMProviderAdapter:

    def test_model_to_entity(self, llm_provider_adapter):
        """Test conversion from SQLAlchemy model to ProviderEntity."""
        # Arrange
        sqlalchemy_model = LLMProviderModel(id=1, name="test_provider")

        # Act
        entity = llm_provider_adapter._model_to_entity(sqlalchemy_model)

        # Assert
        expected_llm_provider_entity_dict = generate_expected_llm_provider_entity_dict(provider_name="test_provider")
        assert entity.model_dump() == expected_llm_provider_entity_dict


    def test_list_providers_default(self, llm_provider_adapter):
        """Upon first startup, OpenAI and Together AI are inserted into DB by default."""        
        # Act
        result: List[ProviderEntity] = llm_provider_adapter.list_providers()

        # Assert
        expected_llm_provider_openai: str = "OpenAI"
        expected_llm_provider_openai_entity_dict = generate_expected_llm_provider_entity_dict(expected_llm_provider_openai)

        expected_llm_provider_togetherai: str = "Together AI"
        expected_llm_provider_togetherai_entity_dict = generate_expected_llm_provider_entity_dict(expected_llm_provider_togetherai)

        assert len(result) == 2, f"Expected 2 providers as OpenAI and TogetherAI are inserted by Alembic by default, instead got {len(result)}."
        for llm_provider_entity in result:
            assert isinstance(llm_provider_entity, ProviderEntity), f"Expected results to be ProviderEntity type, got {type(llm_provider_entity)}."

        result_openai_index: int = next((i for i, llm_provider_entity in enumerate(result) if llm_provider_entity.name==expected_llm_provider_openai), None)
        assert result_openai_index is not None, f"Expected LLM Provider OpenAI is not in result: {result}"
        assert result[result_openai_index].model_dump() == expected_llm_provider_openai_entity_dict, f"Expected LLM Provider OpenAI not in result: {result[result_openai_index]}." 

        result_togetherai_index: int = next((i for i, llm_provider_entity in enumerate(result) if llm_provider_entity.name==expected_llm_provider_togetherai), None)
        assert result_togetherai_index is not None, f"Expected LLM Provider Together AI is not in result: {result}"
        assert result[result_togetherai_index].model_dump() == expected_llm_provider_togetherai_entity_dict, f"Expected LLM Provider Together AI not in result: {result[result_togetherai_index]}." 

        assert result_openai_index < result_togetherai_index, f"Expected OpenAI (index={result_openai_index}) to be before Together AI (index={result_togetherai_index})."
    
    def test_adding_providers(self, llm_provider_adapter):
        """Upon first startup, OpenAI and Together AI are inserted into DB by default."""
        # Act: add 2 LLM Providers to DB, add b before a to test result ordering
        llm_provider_adapter.add_provider("provider_b")
        llm_provider_adapter.add_provider("provider_a")
        result: List[ProviderEntity] = llm_provider_adapter.list_providers()

        # Assert
        expected_llm_provider_a: str = "provider_a"
        expected_llm_provider_a_entity_dict: dict[str, any] = generate_expected_llm_provider_entity_dict(expected_llm_provider_a)

        expected_llm_provider_b: str = "provider_b"
        expected_llm_provider_b_entity_dict: dict[str, any] = generate_expected_llm_provider_entity_dict(expected_llm_provider_b)

        assert len(result) == 4, f"Expected 2 default and 2 added LLM Providers, instead got {len(result)}."
        for llm_provider_entity in result:
            assert isinstance(llm_provider_entity, ProviderEntity), f"Expected results to be ProviderEntity type, got {type(llm_provider_entity)}."

        result_provider_a_index: int = next((i for i, llm_provider_entity in enumerate(result) if llm_provider_entity.name==expected_llm_provider_a), None)
        assert result_provider_a_index is not None, f"Expected LLM Provider A is not in result: {result}"
        assert result[result_provider_a_index].model_dump() == expected_llm_provider_a_entity_dict, f"Expected LLM Provider A not in result: {result[result_provider_a_index]}." 

        result_provider_b_index: int = next((i for i, llm_provider_entity in enumerate(result) if llm_provider_entity.name==expected_llm_provider_b), None)
        assert result_provider_b_index is not None, f"Expected LLM Provider B is not in result: {result}"
        assert result[result_provider_b_index].model_dump() == expected_llm_provider_b_entity_dict, f"Expected LLM Provider B not in result: {result[result_provider_b_index]}." 

        assert result_provider_a_index < result_provider_b_index, f"Expected LLM Provider A (index={result_provider_a_index}) to be before LLM Provider B (index={result_provider_b_index})."
