FROM python:3.12-slim-bookworm AS build

WORKDIR /app

# Create a non-root user and group.
RUN groupadd --system appgroup && \
    useradd --system --uid 1001 --gid appgroup appuser

# Upgrade system packages
RUN apt-get update && apt-get -y upgrade && \
    rm -rf /var/lib/apt/lists/*

# Copy all code into /app
COPY . .

# Install Poetry and dependencies
RUN chown -R appuser:appgroup /app && \
    pip install poetry==2.1.2 --no-cache-dir && \
    poetry config virtualenvs.create false && \
    poetry install

# Switch to the non-root user
USER appuser
