#!/usr/bin/env python3
"""Generate typed feature-flag name constants from feature_flags.txt.

Edit moonshot_core/data/feature_flags.txt, then regenerate via the usual
start/build commands (npm run dev/build, poetry run moonshot-web / run_api.py),
or run this script directly:

    python3 scripts/generate_feature_flags.py
    python3 scripts/generate_feature_flags.py --check

Paths default to the monorepo layout (script lives at <repo>/scripts/).
Override with env vars for alternate layouts (e.g. Docker frontend stage):

    FEATURE_FLAGS_TXT
    FEATURE_FLAGS_PY_OUT
    FEATURE_FLAGS_TS_OUT
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

TRUE_VALUES = frozenset({"true"})
FALSE_VALUES = frozenset({"false"})
FLAG_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

GENERATED_HEADER_PY = (
    "# DO NOT EDIT — generated by scripts/generate_feature_flags.py\n"
    "# Source of truth: moonshot_core/data/feature_flags.txt\n"
)
GENERATED_HEADER_TS = (
    "// DO NOT EDIT — generated by scripts/generate_feature_flags.py\n"
    "// Source of truth: moonshot_core/data/feature_flags.txt\n"
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def default_paths() -> tuple[Path, Path, Path]:
    root = _repo_root()
    return (
        root / "moonshot_core" / "data" / "feature_flags.txt",
        root
        / "moonshot_core"
        / "src"
        / "domain"
        / "services"
        / "enums"
        / "feature_flag_names.py",
        root / "moonshot_portal_app" / "lib" / "featureFlags.ts",
    )


def resolve_paths() -> tuple[Path, Path, Path]:
    default_txt, default_py, default_ts = default_paths()
    txt = Path(os.environ.get("FEATURE_FLAGS_TXT", default_txt))
    py_out = Path(os.environ.get("FEATURE_FLAGS_PY_OUT", default_py))
    ts_out = Path(os.environ.get("FEATURE_FLAGS_TS_OUT", default_ts))
    return txt, py_out, ts_out


def parse_flag_names(content: str) -> list[str]:
    """Parse NAME=true/false lines; return unique names in file order."""
    names: list[str] = []
    seen: set[str] = set()
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise ValueError(f"Invalid feature flag line (missing '='): {raw_line!r}")
        name, raw_value = line.split("=", 1)
        name = name.strip()
        value = raw_value.strip().lower()
        if not name or value not in TRUE_VALUES | FALSE_VALUES:
            raise ValueError(f"Invalid feature flag line: {raw_line!r}")
        if not FLAG_NAME_RE.match(name):
            raise ValueError(f"Invalid feature flag name: {name!r}")
        if name in seen:
            raise ValueError(f"Duplicate feature flag name: {name}")
        seen.add(name)
        names.append(name)
    if not names:
        raise ValueError("No feature flag names found in source file")
    return names


def render_python(names: list[str]) -> str:
    members = "\n".join(f'    {name} = "{name}"' for name in names)
    return (
        f"{GENERATED_HEADER_PY}"
        '"""Generated feature flag name constants."""\n'
        "\n"
        "from enum import StrEnum\n"
        "\n"
        "\n"
        "class FeatureFlagNames(StrEnum):\n"
        '    """Known feature flag names (values match feature_flags.txt keys)."""\n'
        "\n"
        f"{members}\n"
    )


def render_typescript(names: list[str]) -> str:
    members = ",\n".join(f'  {name}: "{name}"' for name in names)
    return (
        f"{GENERATED_HEADER_TS}"
        "export const FeatureFlagNames = {\n"
        f"{members},\n"
        "} as const;\n"
        "\n"
        "export type FeatureFlagName =\n"
        "  (typeof FeatureFlagNames)[keyof typeof FeatureFlagNames];\n"
    )


def generate(check: bool = False) -> int:
    txt_path, py_path, ts_path = resolve_paths()
    if not txt_path.is_file():
        print(f"Feature flags source not found: {txt_path}", file=sys.stderr)
        return 1

    names = parse_flag_names(txt_path.read_text(encoding="utf-8"))
    py_content = render_python(names)
    ts_content = render_typescript(names)

    if check:
        stale = False
        for path, expected in ((py_path, py_content), (ts_path, ts_content)):
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                print(f"Stale or missing generated file: {path}", file=sys.stderr)
                stale = True
        if stale:
            print(
                "Run: python3 scripts/generate_feature_flags.py",
                file=sys.stderr,
            )
            return 1
        print("Feature flag generated files are up to date.")
        return 0

    py_path.parent.mkdir(parents=True, exist_ok=True)
    ts_path.parent.mkdir(parents=True, exist_ok=True)
    py_path.write_text(py_content, encoding="utf-8")
    ts_path.write_text(ts_content, encoding="utf-8")
    print(f"Wrote {py_path}")
    print(f"Wrote {ts_path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate feature flag name constants from feature_flags.txt"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated files are missing or stale",
    )
    args = parser.parse_args(argv)
    try:
        return generate(check=args.check)
    except ValueError as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1


def find_generator_script(start: Path | None = None) -> Path | None:
    """Locate scripts/generate_feature_flags.py by walking parents of start."""
    here = (start or Path(__file__)).resolve()
    search_roots = [here] if here.is_dir() else [here.parent]
    search_roots.extend(here.parents)
    for root in search_roots:
        candidate = root / "scripts" / "generate_feature_flags.py"
        if candidate.is_file():
            return candidate
    return None


def maybe_generate_feature_flags(start: Path | None = None) -> None:
    """
    Run generation when the monorepo script and source file are present.

    No-op in layouts where the generator is absent (e.g. Docker runtime image).
    Raises SystemExit if the generator is present but generation fails.
    """
    script = find_generator_script(start)
    if script is None:
        return
    repo_root = script.parent.parent
    txt_path = Path(
        os.environ.get(
            "FEATURE_FLAGS_TXT",
            repo_root / "moonshot_core" / "data" / "feature_flags.txt",
        )
    )
    py_path = Path(
        os.environ.get(
            "FEATURE_FLAGS_PY_OUT",
            repo_root
            / "moonshot_core"
            / "src"
            / "domain"
            / "services"
            / "enums"
            / "feature_flag_names.py",
        )
    )
    ts_path = Path(
        os.environ.get(
            "FEATURE_FLAGS_TS_OUT",
            repo_root / "moonshot_portal_app" / "lib" / "featureFlags.ts",
        )
    )
    if not txt_path.is_file():
        return
    if not py_path.parent.is_dir() or not ts_path.parent.is_dir():
        # Portal or domain tree missing — skip (Docker runtime).
        return
    previous = {
        "FEATURE_FLAGS_TXT": os.environ.get("FEATURE_FLAGS_TXT"),
        "FEATURE_FLAGS_PY_OUT": os.environ.get("FEATURE_FLAGS_PY_OUT"),
        "FEATURE_FLAGS_TS_OUT": os.environ.get("FEATURE_FLAGS_TS_OUT"),
    }
    os.environ["FEATURE_FLAGS_TXT"] = str(txt_path)
    os.environ["FEATURE_FLAGS_PY_OUT"] = str(py_path)
    os.environ["FEATURE_FLAGS_TS_OUT"] = str(ts_path)
    try:
        code = generate(check=False)
    finally:
        for key, value in previous.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value
    if code != 0:
        raise SystemExit(code)


if __name__ == "__main__":
    sys.exit(main())
