# DO NOT EDIT — generated by scripts/generate_feature_flags.py
# Source of truth: moonshot_core/data/feature_flags.txt
"""Generated feature flag name constants."""

from enum import StrEnum


class FeatureFlagNames(StrEnum):
    """Known feature flag names (values match feature_flags.txt keys)."""

    AIVET_Q42026_MOON774 = "AIVET_Q42026_MOON774"
    AIVET_OCT2026_MOON771 = "AIVET_OCT2026_MOON771"
    AIVET_OCT2026_MOON722 = "AIVET_OCT2026_MOON722"
