"""
FastAPI application for Moonshot CI/CD.
This module provides a REST API interface for the Moonshot benchmarking system.
"""

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from typing import Dict, Any
import os

# Create FastAPI application instance
app = FastAPI(
    title="Moonshot CI/CD API",
    description="A REST API for the Moonshot benchmarking and red-teaming system",
    version="1.1.0",
    docs_url="/docs",
    redoc_url="/redoc"
)


@app.get("/")
async def root():
    """Root endpoint that serves the main HTML file or returns a welcome message."""
    build_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "..", "build")
    index_file = os.path.join(build_dir, "index.html")
    
    if os.path.exists(index_file):
        print(f"Serving index.html from: {index_file}")
        return FileResponse(index_file)
    else:
        print(f"Index file not found at: {index_file}")
        return {"message": "Welcome to Moonshot CI/CD API"}


@app.api_route("/{file_path:path}", methods=["GET", "HEAD"])
async def serve_static_files(file_path: str):
    """Serve static files from the build directory."""
    build_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "..", "build")
    file_path = os.path.join(build_dir, file_path)
    
    # Security check: ensure the file is within the build directory
    if not os.path.abspath(file_path).startswith(os.path.abspath(build_dir)):
        return JSONResponse({"error": "Access denied"}, status_code=403)
    
    if os.path.exists(file_path) and os.path.isfile(file_path):
        return FileResponse(file_path)
    else:
        return JSONResponse({"error": "File not found"}, status_code=404)


@app.get("/health")
async def health_check() -> Dict[str, str]:
    """Health check endpoint."""
    return {"status": "healthy"}


@app.get("/api/v1/status")
async def get_status() -> Dict[str, Any]:
    """Get the current status of the API."""
    return {
        "status": "running",
        "version": "1.1.0",
        "service": "moonshot-cicd"
    }

# -------------------------------------------------------------------------------------------------
# This part assumes that the build directory is located in the ../build directory
# and that the Next.js static files are located in the _next directory
# Those are the default locations for the static files generated by moonshot_portal_app 
# when you call npm run build
# -------------------------------------------------------------------------------------------------
# Mount static files from ../build directory
build_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "..", "build")
if os.path.exists(build_dir):
    # Mount Next.js static files at /_next/ path
    next_static_dir = os.path.join(build_dir, "_next")
    if os.path.exists(next_static_dir):
        app.mount("/_next", StaticFiles(directory=next_static_dir), name="next_static")
        print(f"Next.js static files mounted from: {next_static_dir}")
    
    print(f"Build directory found at: {build_dir}")
    print("Static files will be served via the catch-all route handler")
else:
    print(f"Build directory not found at: {build_dir}")

# Export the FastAPI app for external use
__all__ = ["app"]
