"""
FastAPI application for Moonshot CI/CD.
This module provides a REST API interface for the Moonshot benchmarking system.
"""

from fastapi import FastAPI
from fastapi.responses import JSONResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from typing import Dict, Any
import os

# Create FastAPI application instance
app = FastAPI(
    title="Moonshot CI/CD API",
    description="A REST API for the Moonshot benchmarking and red-teaming system",
    version="1.1.0",
    docs_url="/docs",
    redoc_url="/redoc"
)


@app.get("/")
async def root():
    """Root endpoint that serves the main HTML file or returns a welcome message."""
    build_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "..", "build")
    index_file = os.path.join(build_dir, "index.html")
    
    if os.path.exists(index_file):
        print(f"Serving index.html from: {index_file}")
        return FileResponse(index_file)
    else:
        print(f"Index file not found at: {index_file}")
        return {"message": "Welcome to Moonshot CI/CD API"}


@app.get("/health")
async def health_check() -> Dict[str, str]:
    """Health check endpoint."""
    return {"status": "healthy"}


@app.get("/api/v1/status")
async def get_status() -> Dict[str, Any]:
    """Get the current status of the API."""
    return {
        "status": "running",
        "version": "1.1.0",
        "service": "moonshot-cicd"
    }

# -------------------------------------------------------------------------------------------------
# This part assumes that the build directory is located in the ../build directory
# and that the Next.js static files are located in the _next directory
# Those are the default locations for the static files generated by moonshot_portal_app 
# when you call npm run build
# -------------------------------------------------------------------------------------------------
# Mount static files from ../build directory
build_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "..", "build")
if os.path.exists(build_dir):
    # Mount Next.js static files at /_next/ path
    next_static_dir = os.path.join(build_dir, "_next")
    if os.path.exists(next_static_dir):
        app.mount("/_next", StaticFiles(directory=next_static_dir), name="next_static")
        print(f"Next.js static files mounted from: {next_static_dir}")
    # Also mount general static files at /static/ path
    app.mount("/static", StaticFiles(directory=build_dir), name="static")
    print(f"General static files mounted from: {build_dir}")
else:
    print(f"Build directory not found at: {build_dir}")

# Export the FastAPI app for external use
__all__ = ["app"]
