"""
FastAPI application for Moonshot CI/CD.
This module provides a REST API interface for the Moonshot benchmarking system.
"""

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from typing import Dict, Any
import os
from pathlib import Path
from domain.services.app_config import AppConfig
from domain.services.logger import configure_logger

# Configure the logger for this module
logger = configure_logger(__name__)

# Create FastAPI application instance
app = FastAPI(
    title="Moonshot CI/CD API",
    description="A REST API for the Moonshot benchmarking and red-teaming system",
    version="1.1.0",
    docs_url="/docs",
    redoc_url="/redoc"
)


def get_build_directory() -> Path:
    """Get the build directory path from configuration."""
    app_config = AppConfig()
    build_dir_config = app_config.config.common.get("frontend_build_directory")
    
    # If the path is relative, make it relative to the API file's location
    if not os.path.isabs(build_dir_config):
        api_file_dir = Path(__file__).parent.parent.parent
        return api_file_dir / build_dir_config
    
    return Path(build_dir_config)


@app.get("/")
async def root():
    """Root endpoint that serves the main HTML file or returns a welcome message."""
    build_dir = get_build_directory()
    index_file = build_dir / "index.html"
    
    if index_file.exists():
        logger.info(f"Serving index.html from: {index_file}")
        return FileResponse(str(index_file))
    else:
        logger.warning(f"Index file not found at: {index_file}")
        return {"message": "Welcome to Moonshot CI/CD API"}


@app.api_route("/{file_path:path}", methods=["GET", "HEAD"])
async def serve_static_files(file_path: str):
    """Serve static files from the build directory."""
    build_dir = get_build_directory()
    requested_file = build_dir / file_path
    
    # Security check: ensure the file is within the build directory
    try:
        requested_file.resolve().relative_to(build_dir.resolve())
    except ValueError:
        return JSONResponse({"error": "Access denied"}, status_code=403)
    
    if requested_file.exists() and requested_file.is_file():
        return FileResponse(str(requested_file))
    else:
        return JSONResponse({"error": "File not found"}, status_code=404)

# -------------------------------------------------------------------------------------------------
# This part assumes that the build directory is configured in moonshot_config.yaml
# and that the Next.js static files are located in the _next directory
# Those are the default locations for the static files generated by moonshot_portal_app 
# when you call npm run build
# -------------------------------------------------------------------------------------------------
# Mount static files from configured build directory
build_dir = get_build_directory()
if build_dir.exists():
    # Mount Next.js static files at /_next/ path
    next_static_dir = build_dir / "_next"
    if next_static_dir.exists():
        app.mount("/_next", StaticFiles(directory=str(next_static_dir)), name="next_static")
        logger.info(f"Next.js static files mounted from: {next_static_dir}")
    
    logger.info(f"Build directory found at: {build_dir}")
    logger.info("Static files will be served via the catch-all route handler")
else:
    logger.warning(f"Build directory not found at: {build_dir}")

# Export the FastAPI app for external use
__all__ = ["app"]
