name: pr-dev-main-image-build-test

on:
  # Runs when a pull request to main is being assigned
  pull_request:
    types: [ assigned, synchronize ]
    branches:
      - 'dev_main'
    paths:
      - 'Dockerfile'
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'src/**'  # Triggers when any file inside src/ changes

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t moonshot:test . 
      - name: Run Smoke Tests on Moonshot Image
        run: |
          pwd
          docker run --rm -e OPENAI_API_KEY=${{ secrets.OPENAI_TOKEN }} -v ${{ github.workspace }}/data/results:/app/data/results moonshot:test sh -c "echo Done"
          ls -a /

      - name: Upload Test Results as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: data/results/*
